### ISSUE TITLE
The cell files should be cloned from samples repo.

### ISSUE THREAD

**Issue by anuruddhal** [wso2-cellery/cellery-automation-scripts#22]
**Description:**
At the moment, cell files are committed to the repo under [https://github.com/wso2-cellery/cellery-automation-scripts/tree/master/integration-tests/test-cases/cells](https://github.com/wso2-cellery/cellery-automation-scripts/tree/master/integration-tests/test-cases/cells ) directory. This is wrong as we are maintaining two copies of the same .bal file.

Therefore these resources should be cloned from [cellery/samples](https://github.com/wso2-cellery/samples) repo at the runtime.

**Suggested Labels:**
Improvement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by azinneera** [comment]
Closing since resolved
